namespace BackseatDriver.Core.Abstractions;

/// <summary>
/// Represents an assistant able to generate an <see cref="IAssistantMessage"/> based on a history of <see cref="IMessage"/>s.
/// </summary>
public interface ICompletionProvider
{
    /// <summary>
    /// Generate a new message based on the passed history.
    /// </summary>
    /// <param name="history">The history of messages on which to base the response.</param>
    /// <param name="availableTools">The tools available for this invocation.</param>
    /// <returns>The message generated by the underlying model.</returns>
    public Task<IAssistantMessage> GenerateAsync(IEnumerable<IMessage> history, IEnumerable<ITool> availableTools);
}
