namespace BackseatDriver.Cli.Provider;

/// <summary>
/// Descriptor of a role in a chat.
/// </summary>
public enum ChatRole
{
    /// <summary>
    /// Denotes a system message.
    /// </summary>
    System,

    /// <summary>
    /// Denotes a message sent by the user.
    /// </summary>
    User,

    /// <summary>
    /// Denotes a message generated by a provider
    /// </summary>
    Assistant
}

/// <summary>
/// A message sent as part of an interaction.
/// </summary>
public readonly record struct ChatMessage(ChatRole Sender, string Content);

/// <summary>
/// A message as part of a message history.
/// </summary>
public interface IChatMessage
{
    /// <summary>
    /// Content of the chat message.
    /// </summary>
    public string Content { get; }

    /// <summary>
    /// Whom the message was sent by.
    /// </summary>
    public ChatRole Sender { get; }
}

/// <summary>
/// A system prompt; a message that sets up the behavior of the assistant.
/// </summary>
/// <param name="Content">Content of the system prompt.</param>
public sealed record SystemPrompt(string Content) : IChatMessage
{
    /// <inheritdoc />
    public ChatRole Sender => ChatRole.System;
}

/// <summary>
/// A message sent by the user.
/// </summary>
/// <param name="Content">Content of the message.</param>
public sealed record UserPrompt(string Content) : IChatMessage
{
    /// <inheritdoc />
    public ChatRole Sender => ChatRole.User;
}

/// <summary>
/// A response generated by the assistant.
/// </summary>
/// <param name="Text">The response sent by the assistant.</param>
public sealed record Response(string Text) : IChatMessage
{
    /// <inheritdoc />
    public string Content => $"RESPONSE: {Text}";

    /// <inheritdoc />
    public ChatRole Sender => ChatRole.Assistant;
}

/// <summary>
/// A request to invoke a specific tool, sent by the assistant.
/// </summary>
/// <param name="Invocation">The tool invocation that is being requested.</param>
/// <seealso cref="ToolOutput"/>
public sealed record ToolRequest(string Invocation) : IChatMessage
{
    /// <inheritdoc />
    public string Content => $"TOOL: {Invocation}";

    /// <inheritdoc />
    public ChatRole Sender => ChatRole.Assistant;
}

/// <summary>
/// The result of a tool invocation.
/// </summary>
/// <param name="Result">The output of the invocation.</param>
/// <seealso cref="ToolRequest"/>
public sealed record ToolOutput(string Result) : IChatMessage
{
    /// <inheritdoc />
    public string Content => $"OUTPUT: {Result}";

    /// <inheritdoc />
    public ChatRole Sender => ChatRole.User;
}

/// <summary>
/// A clarifiying question, asked by the assistant.
/// </summary>
/// <param name="Question">The question for the user to answer.</param>
/// <seealso cref="ClarificationAnswer"/>
public sealed record ClarificationRequest(string Question) : IChatMessage
{
    /// <inheritdoc />
    public string Content => $"PROMPT: {Question}";

    /// <inheritdoc />
    public ChatRole Sender => ChatRole.Assistant;
}


/// <summary>
/// The answer to a clarifying question.
/// </summary>
/// <param name="Answer">The answer to the question asked.</param>
/// <seealso cref="ClarificationRequest"/>
public sealed record ClarificationAnswer(string Answer) :IChatMessage
{
    /// <inheritdoc />
    public string Content => $"ANSWER: {Answer}";

    /// <inheritdoc />
    public ChatRole Sender => ChatRole.User;
}
