namespace BackseatDriver.Abstractions.MessageTypes;

/// <summary>
/// A response generated by the assistant.
/// </summary>
/// <param name="text">The response sent by the assistant.</param>
public sealed class AssistantResponse(string text) : AssistantMessageBase
{
    /// <summary>
    /// The response sent by the assistant.
    /// </summary>
    public string Text { get; } = text;

    /// <inheritdoc />
    public override string Content => $"RESPONSE: {Text}";
}
