namespace BackseatDriver.Abstractions.MessageTypes;

/// <summary>
/// A response generated by the assistant.
/// </summary>
/// <param name="text">The response sent by the assistant.</param>
public sealed class AssistantResponse(string text) : AssistantMessageBase
{
    /// <summary>
    /// The prefix for this kind of response.
    /// </summary>
    public const string Prefix = "RESPONSE: ";

    /// <summary>
    /// The response sent by the assistant.
    /// </summary>
    public string Text { get; } = text;

    /// <inheritdoc />
    public override string Content => $"{Prefix}{Text}";
}
