using System.Text.Json.Serialization;

namespace BackseatDriver.OpenAI.Model;

/// <summary>
/// A single message in the current conversation.
/// </summary>
[JsonDerivedType(typeof(SystemMessage))]
[JsonDerivedType(typeof(UserMessage))]
[JsonDerivedType(typeof(FunctionMessage))]
[JsonDerivedType(typeof(AssistantMessage))]
public abstract class ChatCompletionMessageParam
{
    // Poor man's union.
    private ChatCompletionMessageParam() { }

    /// <summary>
    /// Developer-provided instructions that the model should follow, regardless of messages sent by the user.
    /// </summary>
    public sealed class SystemMessage : ChatCompletionMessageParam
    {
        /// <summary>
        /// The role of the messages author.
        /// </summary>
        [JsonPropertyName("role")]
        public string Role => "system";

        /// <summary>
        /// The contents of the system message.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("content")]
        public required string Content { get; init; }
    }

    /// <summary>
    /// A message sent by an end user, containing prompts or additional context information.
    /// </summary>
    public sealed class UserMessage : ChatCompletionMessageParam
    {
        /// <summary>
        /// The role of the messages author.
        /// </summary>
        [JsonPropertyName("role")]
        public string Role => "user";

        /// <summary>
        /// The contents of the user message.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("content")]
        public required string Content { get; init; }
    }

    /// <summary>
    /// The result of invoking a function.
    /// </summary>
    public sealed class FunctionMessage : ChatCompletionMessageParam
    {
        /// <summary>
        /// The role of the messages author.
        /// </summary>
        [JsonPropertyName("role")]
        public string Role => "function";

        /// <summary>
        /// Tool call that this message is responding to.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("tool_call_id")]
        public required string ToolCallId { get; init; }

        /// <summary>
        /// The contents of the function message.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("content")]
        public required string Content { get; init; }
    }

    /// <summary>
    /// A Message sent by the model in response to user messages.
    /// </summary>
    public sealed class AssistantMessage : ChatCompletionMessageParam
    {
        /// <summary>
        /// The role of the messages author.
        /// </summary>
        [JsonPropertyName("role")]
        public string Role => "assistant";

        /// <summary>
        /// The contents of the assistant message.
        /// </summary>
        [JsonPropertyName("content")]
        public string? Content { get; init; }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        [JsonPropertyName("tool_calls")]
        public ChatCompletionFunctionToolCall[]? ToolCalls { get; init; }
    }
}
