using System.Text.Json;
using System.Text.Json.Serialization;

namespace BackseatDriver.OpenAI.Model;

/// <summary>
/// Represents a chat completion response returned by the model, based on the provided input.
/// </summary>
public sealed class ChatCompletionResponse
{
    /// <summary>
    /// A list of chat completion choices.
    /// </summary>
    [JsonRequired]
    [JsonPropertyName("choices")]
    public required ChatCompletionChoice[] Choices { get; init; } = [];

    /// <summary>
    /// A single completion returned by the model.
    /// </summary>
    public sealed class ChatCompletionChoice
    {
        /// <summary>
        /// The reason the model stopped generating tokens.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("finish_reason")]
        public required FinishReason FinishReason { get; init; }

        /// <summary>
        /// The message generated by the model.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("message")]
        public required ChatCompletionMessage Message { get; init; }
    }

    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    public sealed class ChatCompletionMessage
    {
        /// <summary>
        /// The contents of the message.
        /// </summary>
        [JsonPropertyName("content")]
        public string? Content { get; init; }

        /// <summary>
        /// The reasoning generated by the model.
        /// </summary>
        [JsonPropertyName("reasoning_content")]
        public string? Reasoning { get; init; }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        [JsonPropertyName("tool_calls")]
        public ChatCompletionFunctionToolCall[]? ToolCalls { get; init; } = [];
    }

    /// <summary>
    /// The reason the model stopped generating tokens.
    /// </summary>
    [JsonConverter(typeof(FinishReasonConverter))]
    public enum FinishReason
    {
        /// <summary>
        /// The model hit a natural stop point.
        /// </summary>
        Stop,

        /// <summary>
        /// The maximum number of tokens was reached.
        /// </summary>
        Length,

        /// <summary>
        /// Content was omitted.
        /// </summary>
        ContentFilter,

        /// <summary>
        /// The model called a tool.
        /// </summary>
        ToolCalls,

        /// <summary>
        /// The model called a function.
        /// </summary>
        FunctionCalls
    }

    /// <summary>
    /// Specialized JSON converter for <see cref="FinishReason"/>.
    /// </summary>
    public sealed class FinishReasonConverter() : JsonStringEnumConverter<FinishReason>(JsonNamingPolicy.SnakeCaseLower, false);
}
