using System.Text.Json;
using System.Text.Json.Serialization;

namespace BackseatDriver.OpenAI.Model;

/// <summary>
/// A call to a function tool created by the model.
/// </summary>
public sealed class ChatCompletionFunctionToolCall
{
    /// <summary>
    /// The type of the tool.
    /// </summary>
    [JsonPropertyName("type")]
    public string Type => "function";

    /// <summary>
    /// The ID of the tool call.
    /// </summary>
    [JsonRequired]
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// The function that the model called.
    /// </summary>
    [JsonRequired]
    [JsonPropertyName("function")]
    public required FunctionToolCallParams Function { get; init; }

    /// <summary>
    /// A function called by the model.
    /// </summary>
    public sealed class FunctionToolCallParams
    {
        /// <summary>
        /// The name of the function to call.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("name")]
        public required string Name { get; init; }

        /// <summary>
        /// The arguments to call the function with, as generated by the model in JSON format.
        /// </summary>
        [JsonRequired]
        [JsonPropertyName("arguments")]
        public JsonDocument Arguments { get; init; } = JsonDocument.Parse("{}");
    }
}
