namespace BackseatDriver.Abstractions;

/// <summary>
/// Descriptor of a role in a chat.
/// </summary>
public enum ChatRole
{
    /// <summary>
    /// Denotes a system message.
    /// </summary>
    System,

    /// <summary>
    /// Denotes a message sent by the user.
    /// </summary>
    User,

    /// <summary>
    /// Denotes a message generated by a provider
    /// </summary>
    Assistant
}
