namespace BackseatDriver.Abstractions;

/// <summary>
/// A response generated by an assistant.
/// </summary>
/// <param name="Message">The message that was generated.</param>
public sealed record GeneratedResponse(AssistantMessageBase Message)
{
    /// <summary>
    /// The reasoning message generated by the assistant.
    /// </summary>
    /// <remarks>
    /// Only set if supported by the <see cref="IProvider"/>.
    /// </remarks>
    public string? ReasoningMessage { get; init; }
}
